development:
  adapter: postgresql
  encoding: utf8
  database: jobhopper_development
  pool: 5
  username: 
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: jobhopper_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: jobhopper_production
  pool: 5
  username: 
  password: